version: '3'

services:
  web:
    image: bandundu/briefbox:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SECRET_KEY=${SECRET_KEY}